apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: psql-rhsn-jfrog
  namespace: postgres-cluster
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  shutdown: false
  image: registry.crunchydata.com/crunchydata/crunchy-postgres:ubi9-16.8-2513
  imagePullSecrets:
    - name: crunchy-regcred
  postgresVersion: 16
  users:
    - name: hippo
      databases:
        - zoo
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: "standard"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
    - name: instance2
      dataVolumeClaimSpec:
        storageClassName: "standard"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi